### ISSUE TITLE
public class ConvertCent seems to round

### ISSUE THREAD

**Issue by pflegefall** [Hunv/can2mqtt#10]
Hi,
using the Translation for the Gradient of HC1 ("MqttTopic": "/heatcircle/hc1/gradient",)
Value of "30" is translated to "0".
Running translation with Default delivers "30" which is ok for me as a temp. workaround.

**Comment by Hunv** [comment]
Hi, I will check this and fix this in the next release probably end of the year.

**Comment by Hunv** [comment]
Fixed in current code. Will be also fixed in next release.
