### ISSUE TITLE
Typo "Humidtiy" in topic "Humidity"

### ISSUE THREAD

**Issue by pflegefall** [Hunv/can2mqtt#12]
Hi,
VERY GREAT Tool, and special Thanks to all contributions!

Please find this hint, that there is a typo in humidity related topics on mqtt:

Can be fixed in lines 6958, 7030 and 10241 in translation file StiebelEltron.json

**Comment by Hunv** [comment]
Hi, I will check this and fix this in the next release probably end of the year.

**Comment by Hunv** [comment]
fixed in code. Will also be fixed in next release.
