### ISSUE TITLE
Problem while installing can2mqtt

### ISSUE THREAD

**Issue by Klaus-Guenther** [Hunv/can2mqtt#17]
First at all:
I do have an PICAN 2! an Raspberry Pi 3.

When i try to set up the connection between my Tecalor WPM (3) which should be the same as Stiebel Eltron WPM 3, i can see that many data can be read via:

pi@raspberrypi:~ $ sudo systemctl status socketcand
● socketcand.service - socketcand
     Loaded: loaded (/etc/systemd/system/socketcand.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-07-02 13:30:41 BST; 6h ago
   Main PID: 507 (socketcand)
      Tasks: 2 (limit: 1595)
        CPU: 17ms
     CGroup: /system.slice/socketcand.service
             ├─507 /opt/socketcand/socketcand -i slcan0 -l eth0 -v
             └─640 /opt/socketcand/socketcand -i slcan0 -l eth0 -v

Jul 02 13:30:41 raspberrypi systemd[1]: Started socketcand.

pi@raspberrypi:~ $ candump can0
  can0  480   [7]  A0 00 2C 00 00 00 00
  can0  180   [7]  A0 79 0C 00 B9 00 00
  can0  480   [7]  A0 00 2C 00 00 00 00
.....
....
..
.

So i think, that data from the can bus can read via the pican2 and the sofware.

Problems beginn, when i try so send data via mqtt to my openhab system:

pi@raspberrypi:~ $ sudo systemctl status can2mqtt
● can2mqtt.service - can2mqtt
     Loaded: loaded (/etc/systemd/system/can2mqtt.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-07-02 13:30:47 BST; 6h ago
   Main PID: 566 (dotnet)
      Tasks: 20 (limit: 1595)
        CPU: 3.186s
     CGroup: /system.slice/can2mqtt.service
             └─566 dotnet /opt/can2mqtt/can2mqtt.dll

Jul 02 13:30:54 raspberrypi dotnet[566]: CONNECTED TO SOCKETCAND 192.168.178.251 ON PORT 29536
Jul 02 13:30:54 raspberrypi dotnet[566]: Handshake successful. Opening CAN interface...
Jul 02 13:30:54 raspberrypi dotnet[566]: Opening connection to slcan0 successful. Changing socketcand mode to raw...
Jul 02 13:30:54 raspberrypi dotnet[566]: Change to rawmode successful
Jul 02 13:30:54 raspberrypi dotnet[566]: Error while reading CanBus Server. System.FormatException: Input string was not in a correct format.
Jul 02 13:30:54 raspberrypi dotnet[566]:    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
Jul 02 13:30:54 raspberrypi dotnet[566]:    at System.Convert.ToInt64(String value, IFormatProvider provider)
Jul 02 13:30:54 raspberrypi dotnet[566]:    at can2mqtt.CanFrame.set_RawFrame(String value) in D:\Productions\#git\can2mqtt\can2mqtt_core\can2mqtt_core\CanFrame.>
Jul 02 13:30:54 raspberrypi dotnet[566]:    at can2mqtt.Can2Mqtt.TcpCanBusListener(String canServer, Int32 canPort) in D:\Productions\#git\can2mqtt\can2mqtt_core>
Jul 02 13:30:54 raspberrypi dotnet[566]: Already connected to SocketCanD.

pi@raspberrypi:~ $ dotnet /opt/can2mqtt/can2mqtt.dll
Cannot find config.json. Copy and rename the config-sample.json and adjust your settings in that config file.
DISCONNECTED FROM MQTT BROKER
DISCONNECTED FROM MQTT BROKER
RECONNECTING TO MQTT BROKER  FAILED
DISCONNECTED FROM MQTT BROKER
RECONNECTING TO MQTT BROKER  FAILED
DISCONNECTED FROM MQTT BROKER
RECONNECTING TO MQTT BROKER  FAILED
RECONNECTING TO MQTT BROKER  FAILED
Unhandled exception. MQTTnet.Exceptions.MqttCommunicationException: Value cannot be null. (Parameter 'host')
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'host')
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapAndThrowException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at can2mqtt.Can2Mqtt.StartAsync(CancellationToken stoppingToken) in D:\Productions\#git\can2mqtt\can2mqtt_core\can2mqtt_core\can2mqtt.cs:line 150
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in D:\Productions\#git\can2mqtt\can2mqtt_core\can2mqtt_core\Program.cs:line 12
   at Program.<Main>(String[] args)
Aborted

Has someone an idea which could be wrong?

**Comment by Hunv** [comment]
For the 
`pi@raspberrypi:~ $ dotnet /opt/can2mqtt/can2mqtt.dll`
command: 
Can you change to /opt/can2mqtt first before running this command? Does it also tell you the config.json is missing?

For the service status:
The error is this line:
`Error while reading CanBus Server. System.FormatException: Input string was not in a correct format.`
I guess regarding the error it is in this line for the CanFrame.cs file:   
`Timestamp = Convert.ToInt64(dataFrame.Substring(0, 10), new CultureInfo("en-US"));`
So it seems something with the dataFrame, send by socketcand, is not correct.
I will try to implement improved logging the next days, so it will be possible to set log levels. That way I will add, that by default the frames are not logged, but if the loglevel is set to debug or trace, it will be logged.

**Comment by Klaus-Guenther** [comment]
Then this happend:

.....
...
.
CONNECTED TO MQTT BROKER 192.168.178.16 using ClientId Can2Mqtt
DISCONNECTED FROM MQTT BROKER 192.168.178.16
CONNECTED TO MQTT BROKER 192.168.178.16 using ClientId Can2Mqtt
.
..
...
....

**Comment by Hunv** [comment]
@Klaus-Guenther : Are there any changes or new things to know?

**Comment by Hunv** [comment]
No further response. Ticket closed.
