### ISSUE TITLE
Kontaktaufnahme

### ISSUE THREAD

**Issue by Xtremdiver** [Hunv/can2mqtt#3]
Hi Hunv,

ich habe deine Beiträge hier und im Haustechnik Forum gelesen.
Ich selber habe eine LWZ 504 über einen USBtin mit dem Raspberry Pi verbunden.
Das Programm läuft super, wenn auch die Installation nicht reibungslos gelang (Anleitung nicht schlecht https://nocloud.info/en/attach-stiebel-eltron-lwz-504-using-usbtin-and-can-bus/ -> hat aber einige Fehler drin)

Nun empfange ich auch die ersten MQTT Einträge und habe ein paar Fragen bzw. Anregungen zur Verbesserung.
1. Kann man irgendwo die Zeit der Abfrage für die Temperaturwerte welche alle 10 Sekunden eintreffen (wie "flow/temperature/measured") auf 60 Sekunden erhöhen?
Außerdem nutze ich OpenHAB und da werden die Temperaturen momentan nur als Ganzzahl erkannt. Das liegt daran, dass OpenHAB ein Punkt als Trennung haben möchte. Dein Programm aber ein Komma sendet. Kann man das irgendwo einstellen?

2. Die Zuordnung der CAN-BUS Telegramme zu den MQTT Einträgen sind nicht stimmig. Hierzu habe ich eine List angefertigt, welche ich gern einspielen würde. Weiß aber nicht wo ich das machen kann, da mit einer kompilierten *.dll gearbeitet wird.

Hier meine Liste von der LWZ 504:
Info -> Laufzeiten
180#D221FA05A415EA	15EA = 5610	[h] Laufzeit Verdichter Heizen
180#D221FA05A50000	0000 =    0	[h] Laufzeit Verdichter Kühlen (kann nicht zu 100% bestätigt werden, da 05A7 ebenfalls 0 ist)
180#D221FA05A601DB	01DB =  475	[h] Laufzeit Verdichter Warmwasser
180#D221FA05A70001	0001 =    1	[h] Elektrisch NE WW
180#D221FA05A80000	0000 =    0	[h] Elektrisch NE Heizen (kann nicht zu 100% bestätigt werden, da 05A7 ebenfalls 0 ist)

Info -> Wärmemenge
180#D221FA092E03DF	03DF = 991	[ Wh] Wärmemenge Heizen Tag
180#D221FA092F0021	0021 =  33	[kWh] Wärmemenge Heizen Tag
180#D221FA093002FE	02FE = 766	[ Wh] Wärmemenge Heizen Summe
180#D221FA09310014	0014 =  20	[kWh] Wärmemenge Heizen Summe
180#D221FA092A004A	004A =  74	[ Wh] Wärmemenge Warmwasser Tag
180#D221FA092B0002	0002 =   2	[kWh] Wärmemenge Warmwasser Tag
180#D221FA092C0212	0212 = 530	[ Wh] Wärmemenge Warmwasser Summe
180#D221FA092D0002	0002 =   2	[kWh] Wärmemenge Warmwasser Summe
180#D221FA09280000	0000 =   0	[ Wh] Wärmemenge NE Heizen Summe
180#D221FA09290000	0000 =   0	[kWh] Wärmemenge NE Heizen Summe
180#D221FA09240006	0006 =   6	[ Wh] Wärmemenge Warmwasser Summe
180#D221FA09250000	0000 =   0	[kWh] Wärmemenge Warmwasser Summe
180#D221FA03AE02F1	02F1 = 753	[ Wh] Wärmemenge Wärmerückgewinnung Tag
180#D221FA03AF0012	0012 =  18	[kWh] Wärmemenge Wärmerückgewinnung Tag		Übersetzt in -> heating/recoverydaywh = 18
180#D221FA03B001C4	01C4 = 452	[kWh] Wärmemenge Wärmerückgewinnung Summe	Übersetzt in -> heating/recoverydaykwh 452
180#D221FA03B10000	0000 =   0	[MWh] Wärmemenge Wärmerückgewinnung Summe	Übersetzt in -> heating/heatrecoverysumkwh 0
180#D221FA06400000	0000 =   0	[ Wh] Wärmemenge Solar Heizung Tag
180#D221FA06410000	0000 =   0	[kWh] Wärmemenge Solar Heizung Tag
180#D221FA06420000	0000 =   0	[ Wh] Wärmemenge Solar Heizung Summe (könnte auch kWh sein)
180#D221FA06430000	0000 =   0	[kWh] Wärmemenge Solar Heizung Summe (könnte auch MWh sein)
180#D221FA06440000	0000 =   0	[ Wh] Wärmemenge Solar Warmwasser Tag
180#D221FA06450000	0000 =   0	[kWh] Wärmemenge Solar Warmwasser Tag
180#D221FA06460000	0000 =   0	[ Wh] Wärmemenge Solar Warmwasser Summe (könnte auch kWh sein)
180#D221FA06470000	0000 =   0	[kWh] Wärmemenge Solar Warmwasser Summe (könnte auch MWh sein)
180#D221FA06480000	0000 =   0	[ Wh] Wärmemenge Kühlen Summe (könnte auch kWh sein)
180#D221FA06490000	0000 =   0	[kWh] Wärmemenge Kühlen Summe (könnte auch kWh sein)

Wie gesagt, ich würde gerne meinen Beitrag zu diesem schönen Programm leisten.

VG
Peter (Xtremdiver)

**Comment by Hunv** [comment]
Hi Peter,
leider habe ich dein Issue erst jetzt gesehen. Zu deinen Fragen:
1. Nein. Can2Mqtt ist ja nur ein forwarder. Die Heizung schickt regelmäßig diese Daten und entsprechend werden diese auch im gleichen Moment weitergeleitet. Zum Komma/Punkt: Es sollte mit dem neusten Update immer ein Punkt sein. Du könntest es in OpenHAB über einen Converter aber auch konvertieren.
2. Mit dem neusten Release sind auch die Werte einmal alle (gegen eine LWZ 504) validiert worden. Zudem befinden diese sich nun in einer Standard-Json-Datei und können frei angepasst werden. Achtung: Die Liste ist lang.
