### ISSUE TITLE
Feature request: Send untranslated can package to topic /heating/<index>

### ISSUE THREAD

**Issue by xylone** [Hunv/can2mqtt#6]
Hi,

Is there a way for you to send the data in all forms you can think of if it is not in the translate table?
For instance:
When I send index 0111 you return:
/heating/0111
  -> value in raw
  -> value in dec
  -> value in hex
  -> value in bit
  -> value in little endian
  -> value in bool

That would be great to determine which index is what and complete/increment the translation table. (I already added some, which I found by trial and error: 0x01D4 => Source (Quelle) temperature

Because the Elster table does not match my heat pump. (A lot does, but also a lot not)

**Comment by Hunv** [comment]
Hi @xylone,
sorry for late answer. I think I have to edit my github message settings ;)
Have you tried to use the can2mqtt_tool to get this? That one has already such an output.

**Comment by Hunv** [comment]
Hi @xylone ,
in the sourcecode of this project is a tool called can2mqtt_tool.
If you run it with 
`can2mqtt_tool.exe -c 0815 -t StiebelEltron`
you get what you want, I think. Of cause it is not doing a "live log", but after you got a new unknown value, you can put it in there. I will add a compiled version of the tool to the next release.

**Comment by Hunv** [comment]
No further response. Closing issue.
